name: Node.js CI

on:
  push:
    branches: [ workflows ]

env: 
  MONGO_URI: mongodb+srv://gjs5758:guardianangel1@cluster0.p2ion.mongodb.net/?retryWrites=true&w=majority
  PORT: 8000
  SECRET: ninjadojoshifuyoshimarioluigipeachbowser
  
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.14.2]

    steps:
      - name: 'Create env file'
        run: |
          touch .env
          echo PORT=8000 >> .env
          echo MONGO_URI=mongodb+srv://gjs5758:guardianangel1@cluster0.p2ion.mongodb.net/?retryWrites=true&w=majority >> .env
          echo SECRET=ninjadojoshifuyoshimarioluigipeachbowser >> .env
          cat .env
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: cd backend
      - run: |
            cd backend
            npm install
      - run: |
            cd backend 
            npm run start
  automated-api-tests:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Install Postman CLI
          run: |
            curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
        - name: Login to Postman CLI
          run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
        - name: Delay
          run: sleep 20s
          shell: bash 
        - name: Run API tests
          run: |
            postman collection run "20858588-fc30274c-d622-4027-9e48-68d2dff5a46b" -e "20858588-a6b23f02-b192-4f22-803b-b14919a8c398"
